### ISSUE TITLE
Profile card styling

### ISSUE THREAD

**Issue by ArshMalik02** [uclaacm/membership-portal-ui#110]
When someone clicks on a profile on the leaderboard, it pops up a profile card. If the name or major is a long text, it just overflows out of the card. Ideally, the card should resize itself based on its contents.

Here is an image for reference:
<img width="675" alt="Screenshot 2023-10-12 at 5 28 03 PM" src="https://github.com/uclaacm/membership-portal-ui/assets/51771221/4f9929a3-eb45-4efc-9c8f-3d36dfb8e77b">

**Comment by WhiteNight110** [comment]
Can you assign it to me? I can try to fix it.
