### ISSUE TITLE
Disabled buttons are still clickable

### ISSUE THREAD

**Issue by ramsgoli** [uclaacm/membership-portal-ui#42]
Disabled buttons (like on the profile page) still register click events
<img width="499" alt="screen shot 2018-03-30 at 7 23 22 pm" src="https://user-images.githubusercontent.com/12592200/38158785-d669c2e4-344f-11e8-9b5d-ce3236c3000f.png">

**Comment by nkansal96** [comment]
Deadline: **05/25**

**Comment by alexanderqchen** [comment]
https://github.com/uclaacm/membership-portal-ui/commit/be2b9903815a5a0cf0104e46c2effed4052925a8
