### ISSUE TITLE
Default max length for URL

### ISSUE THREAD

**Issue by GalenWong** [uclaacm/membership-portal-ui#81]
Hi, Dev team,

You guys are doing great work. One issue that we ran into constantly is that the URL field for creating an event is limited to 255 characters, but facebook's image assets URLs are usually super-duper long, which does not fit into the field. 

https://github.com/uclaacm/membership-portal/blob/28afadbde8bac569c64a127af87101c08ccebd92/app/db/schema/event.js#L51

Can we increase that limit?

Thank you guys so much!

**Comment by mattxwang** [comment]
@GalenWong did we ever get back to you on this? If this is still a problem, I can probably just make the change.

**Comment by advaithg** [comment]
Going to bring this ticket back, assigning to @samarthupadhyaya27

**Comment by dtjanaka** [comment]
wrong repo, should be in membership-portal

**Comment by mattxwang** [comment]
FYI in the future, there's a "transfer issue" button that moves the issue to another repo but keeps the history, etc.!
