### ISSUE TITLE
Add space between in and month name

### ISSUE THREAD

**Issue by kristielim** [uclaacm/membership-portal-ui#82]
In `eventMonth.js` (also this should be `.jsx`), change to
```
<h1 className="Display-2Primary date-month">Events in {this.props.month.date.format("MMMM")}</h1>
```
This fixes the problem that looks like
<img width="490" alt="Screen Shot 2019-10-14 at 8 51 10 PM" src="https://user-images.githubusercontent.com/28357052/66800546-68c42400-eeca-11e9-9d7c-4836949d4dcb.png">

**Comment by howardwang15** [comment]
Resolved
